# Dependencies
markdown:         rdiscount
highlighter:	  pygments

# Permalinks
permalink:        pretty

# Server
source:           ./src/docs
destination:      ./docs
host:             localhost
port:             9001
baseurl:          ../../../../
url:              http://localhost:9001
encoding:         UTF-8

# exclude:          ['*.less']

# Custom variables
current_version:  0.5.0
repo:             https://github.com/rwd-pine/pine.git
