# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           ./src/docs
destination:      ./docs
host:             0.0.0.0
port:             9001
baseurl:          ../../../../
url:              http://localhost:9001
encoding:         UTF-8

# exclude:          ['*.less']

# Custom variables
current_version:  0.0.1
repo:             https://github.com/rwd-pine/pine.git
